### ISSUE TITLE
Apparent incompatibility with Et Futurum Requiem

### ISSUE THREAD

**Issue by Gronglegrowth** [makamys/RenderPlayerAPI#1]
Received this crash while entering a world with Et Futurum Requiem installed alongside this.

[crash-2023-02-03_18.10.36-client.txt](https://github.com/makamys/RenderPlayerAPI/files/10583466/crash-2023-02-03_18.10.36-client.txt)

**Comment by makamys** [comment]
EFR's skin renderer is known to cause issues with other mods, you can disable it and try SkinPort instead which has explicit compatibility with RenderPlayerAPI.

I'll close this because there isn't anything that can be realistically done on this mod's side.
